-- Metadata schema for the migration scheduler.
-- Kept portable between PostgreSQL (default) and H2 in PostgreSQL mode (local profile / tests).

CREATE TABLE connection_def (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100)  NOT NULL,
    kind          VARCHAR(10)   NOT NULL,
    db_type       VARCHAR(20)   NOT NULL,
    uri           VARCHAR(2000),
    host          VARCHAR(255),
    port          INTEGER,
    database_name VARCHAR(255),
    username      VARCHAR(255),
    password_enc  VARCHAR(1000),
    options_json  VARCHAR,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_connection_def_name UNIQUE (name)
);

CREATE TABLE migration_job (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               VARCHAR(100) NOT NULL,
    source_conn_id     BIGINT       NOT NULL,
    target_conn_id     BIGINT       NOT NULL,
    cron               VARCHAR(120),
    timezone           VARCHAR(64)  NOT NULL,
    enabled            BOOLEAN      NOT NULL,
    sync_mode          VARCHAR(20)  NOT NULL,
    batch_size         INTEGER      NOT NULL,
    write_mode         VARCHAR(30)  NOT NULL,
    auto_create_schema BOOLEAN      NOT NULL,
    max_retries        INTEGER      NOT NULL,
    version            BIGINT       NOT NULL,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_migration_job_name UNIQUE (name),
    CONSTRAINT fk_job_source_conn FOREIGN KEY (source_conn_id) REFERENCES connection_def (id),
    CONSTRAINT fk_job_target_conn FOREIGN KEY (target_conn_id) REFERENCES connection_def (id)
);

CREATE TABLE collection_mapping (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id            BIGINT       NOT NULL,
    source_collection VARCHAR(255) NOT NULL,
    target_table      VARCHAR(255) NOT NULL,
    mapping_json      VARCHAR      NOT NULL,
    watermark_field   VARCHAR(255),
    filter_json       VARCHAR,
    order_index       INTEGER      NOT NULL,
    CONSTRAINT fk_mapping_job FOREIGN KEY (job_id) REFERENCES migration_job (id) ON DELETE CASCADE
);
CREATE INDEX ix_collection_mapping_job ON collection_mapping (job_id);

CREATE TABLE checkpoint (
    collection_mapping_id BIGINT PRIMARY KEY,
    job_id                BIGINT NOT NULL,
    last_id               VARCHAR(255),
    last_watermark        VARCHAR(255),
    updated_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_checkpoint_mapping FOREIGN KEY (collection_mapping_id) REFERENCES collection_mapping (id) ON DELETE CASCADE,
    CONSTRAINT fk_checkpoint_job FOREIGN KEY (job_id) REFERENCES migration_job (id) ON DELETE CASCADE
);

CREATE TABLE job_run (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id        BIGINT      NOT NULL,
    trigger_type  VARCHAR(10) NOT NULL,
    status        VARCHAR(20) NOT NULL,
    started_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    ended_at      TIMESTAMP WITH TIME ZONE,
    docs_read     BIGINT      NOT NULL,
    rows_written  BIGINT      NOT NULL,
    docs_failed   BIGINT      NOT NULL,
    error_message VARCHAR(4000),
    CONSTRAINT fk_run_job FOREIGN KEY (job_id) REFERENCES migration_job (id) ON DELETE CASCADE
);
CREATE INDEX ix_job_run_job_started ON job_run (job_id, started_at);

CREATE TABLE dead_letter_record (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id          BIGINT       NOT NULL,
    collection_name VARCHAR(255) NOT NULL,
    source_id       VARCHAR(255),
    payload_json    VARCHAR,
    error           VARCHAR(4000),
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_dead_letter_run FOREIGN KEY (run_id) REFERENCES job_run (id) ON DELETE CASCADE
);
CREATE INDEX ix_dead_letter_run ON dead_letter_record (run_id);
